// Auth Types
export const USER_ERROR = "USER/ERROR";
export const USER_LOGIN = "USER/LOGIN";
export const USER_LOGOUT = "USER/LOGOUT";
export const USER_RESET = "USER/RESET";
export const USER_SET_USERNAME = "USER/SET_USERNAME";

// Content Types
export const BODY_ERROR = "BODY/ERROR";
export const BODY_GET = "BODY/GET";
export const BODY_SAVE = "BODY/SAVE";
export const BODY_SET_SAVED_CHANGES = "BODY/SET_SAVED_CHANGES";
export const BODY_LOADING = "BODY/LOADING";
export const BODY_SET_DISPLAY_LOGIN = "BODY/SET_DISPLAY_LOGIN";
export const BODY_RESET = "BODY/RESET";
export const EDIT_SET_VISAGE_NAME = "EDIT/SET_VISAGE_NAME";
export const EDIT_INSERT = "EDIT/INSERT";
export const EDIT_DELETE = "EDIT/DELETE";
export const EDIT_DELETE_CHILDREN = "EDIT/DELETE_CHILDREN";
export const EDIT_MOVE = "EDIT/MOVE";
export const EDIT_SET_INNER = "EDIT/SET_INNER";
export const EDIT_SET_PROPS = "EDIT/SET_PROPS";
export const EDIT_SET_SELECTED = "EDIT/SET_SELECTED";
export const EDIT_DISABLE_PARENT = "EDIT/DISABLE_PARENT";
export const EDIT_ENABLE_PARENT = "EDIT/ENABLE_PARENT";
export const EDIT_TOGGLE = "EDIT/TOGGLE";
export const EDIT_SET_EDITING = "EDIT/SET_EDITING";

// Error Types
export const ERROR_AUTH_USERNAME = "ERROR/AUTH_USERNAME";
export const ERROR_AUTH_PASSWORD = "ERROR/AUTH_PASSWORD";
export const ERROR_LOGIN = "ERROR/LOGIN";
export const ERROR_REGISTER = "ERROR/REGISTER";
export const ERROR_GET_VISAGE = "ERROR/GET_VISAGE";
export const ERROR_SAVE_VISAGE = "ERROR/SAVE_VISAGE";
export const ERROR_RESET = "ERROR/RESET";

// Nav Types
export const NAV_TOGGLE = "NAV/TOGGLE";
export const NAV_RESET = "NAV/RESET";
export const TOOLS_TOGGLE = "TOOLS/TOGGLE";
export const TOOLS_SET_TOOLS = "TOOLS/SET_TOOLS";
export const TOOLS_SET_VIEW = "TOOLS/SET_VIEW";
